// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/JerryZhou343/bup/internal/compile"
	"github.com/JerryZhou343/bup/internal/conf"
	"github.com/JerryZhou343/bup/internal/format"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	config := conf.NewConfig()
	compiler := compile.NewCompiler(config)
	formatter := format.NewFormatter()
	app := NewApp(config, compiler, formatter)
	return app, nil
}
