// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/mfslog/prototool/internal/compile"
	"github.com/mfslog/prototool/internal/conf"
	"github.com/mfslog/prototool/internal/format"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	config, err := conf.NewConfig()
	if err != nil {
		return nil, err
	}
	compiler := compile.NewCompiler(config)
	formatter := format.NewFormatter()
	app, err := NewApp(config, compiler, formatter)
	if err != nil {
		return nil, err
	}
	return app, nil
}
